// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureChat.Models;

#nullable disable

namespace SecureChat.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SecureChat.Models.BlockedUser", b =>
                {
                    b.Property<string>("BlockID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("block_id");

                    b.Property<string>("BlockedID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("blocked_id");

                    b.Property<string>("BlockerID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("blocker_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("BlockID");

                    b.HasIndex("BlockedID");

                    b.HasIndex("BlockerID")
                        .HasDatabaseName("idx_is_blocked");

                    b.HasIndex("BlockerID", "BlockedID")
                        .IsUnique()
                        .HasDatabaseName("uq_block_pair");

                    b.ToTable("BlockedUsers");

                    b.HasData(
                        new
                        {
                            BlockID = "B0000001",
                            BlockedID = "U0000003",
                            BlockerID = "U0000002",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 8, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SecureChat.Models.CallLog", b =>
                {
                    b.Property<string>("CallID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("call_id");

                    b.Property<string>("ConversationID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("StartedBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("started_by");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("call_type");

                    b.HasKey("CallID");

                    b.HasIndex("ConversationID")
                        .HasDatabaseName("idx_call_logs_conversation");

                    b.HasIndex("StartedBy");

                    b.ToTable("CallLogs");

                    b.HasData(
                        new
                        {
                            CallID = "CL000001",
                            ConversationID = "C0000002",
                            EndedAt = new DateTime(2025, 1, 10, 8, 28, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 1, 10, 8, 24, 0, 0, DateTimeKind.Utc),
                            StartedBy = "M0000003",
                            Status = (byte)2,
                            Type = (byte)0
                        });
                });

            modelBuilder.Entity("SecureChat.Models.CallParticipant", b =>
                {
                    b.Property<string>("ParticipantID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("participant_id");

                    b.Property<string>("CallID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("call_id");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("left_at");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.HasKey("ParticipantID", "CallID");

                    b.HasIndex("CallID");

                    b.HasIndex("ParticipantID")
                        .HasDatabaseName("idx_call_participants_user");

                    b.ToTable("CallParticipants");

                    b.HasData(
                        new
                        {
                            ParticipantID = "M0000003",
                            CallID = "CL000001",
                            JoinedAt = new DateTime(2025, 1, 10, 8, 24, 0, 0, DateTimeKind.Utc),
                            LeftAt = new DateTime(2025, 1, 10, 8, 28, 0, 0, DateTimeKind.Utc),
                            Status = (byte)1
                        },
                        new
                        {
                            ParticipantID = "M0000004",
                            CallID = "CL000001",
                            JoinedAt = new DateTime(2025, 1, 10, 8, 24, 0, 0, DateTimeKind.Utc),
                            LeftAt = new DateTime(2025, 1, 10, 8, 28, 0, 0, DateTimeKind.Utc),
                            Status = (byte)1
                        },
                        new
                        {
                            ParticipantID = "M0000005",
                            CallID = "CL000001",
                            Status = (byte)3
                        });
                });

            modelBuilder.Entity("SecureChat.Models.Conversation", b =>
                {
                    b.Property<string>("ConversationID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("conversation_id");

                    b.Property<string>("AvatarURL")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("LastMessageID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("last_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("conversation_type");

                    b.HasKey("ConversationID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastActivityAt")
                        .IsDescending()
                        .HasDatabaseName("idx_conv_activity");

                    b.HasIndex("LastMessageID");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            ConversationID = "C0000001",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 12, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "U0000001",
                            LastActivityAt = new DateTime(2025, 1, 10, 8, 21, 0, 0, DateTimeKind.Utc),
                            Type = (byte)0
                        },
                        new
                        {
                            ConversationID = "C0000002",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 12, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "U0000001",
                            LastActivityAt = new DateTime(2025, 1, 10, 8, 28, 0, 0, DateTimeKind.Utc),
                            Name = "NT106 Team",
                            Type = (byte)1
                        });
                });

            modelBuilder.Entity("SecureChat.Models.ConversationMember", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("member_id");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("banned_until");

                    b.Property<string>("ConversationID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("conversation_id");

                    b.Property<string>("EncryptedKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("encrypted_key");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("LastReadMsgID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("last_read_msg_id");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("left_at");

                    b.Property<string>("Nickname")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("nickname");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("role");

                    b.Property<byte>("ShowNotifications")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("show_notifications");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("user_id");

                    b.HasKey("MemberID");

                    b.HasIndex("LastReadMsgID");

                    b.HasIndex("UserID")
                        .HasDatabaseName("idx_conv_members_user");

                    b.HasIndex("ConversationID", "UserID")
                        .IsUnique()
                        .HasDatabaseName("uq_convmems_user");

                    b.ToTable("ConversationMembers");

                    b.HasData(
                        new
                        {
                            MemberID = "M0000001",
                            ConversationID = "C0000001",
                            EncryptedKey = "encrypted_demo_value",
                            JoinedAt = new DateTime(2025, 1, 10, 8, 12, 0, 0, DateTimeKind.Utc),
                            Nickname = "Hieu",
                            Role = (byte)2,
                            ShowNotifications = (byte)2,
                            UserID = "U0000001"
                        },
                        new
                        {
                            MemberID = "M0000002",
                            ConversationID = "C0000001",
                            EncryptedKey = "encrypted_demo_value",
                            JoinedAt = new DateTime(2025, 1, 10, 8, 12, 0, 0, DateTimeKind.Utc),
                            Nickname = "Quan",
                            Role = (byte)0,
                            ShowNotifications = (byte)2,
                            UserID = "U0000002"
                        },
                        new
                        {
                            MemberID = "M0000003",
                            ConversationID = "C0000002",
                            EncryptedKey = "encrypted_demo_value",
                            JoinedAt = new DateTime(2025, 1, 10, 8, 12, 0, 0, DateTimeKind.Utc),
                            Nickname = "Admin Hieu",
                            Role = (byte)2,
                            ShowNotifications = (byte)2,
                            UserID = "U0000001"
                        },
                        new
                        {
                            MemberID = "M0000004",
                            ConversationID = "C0000002",
                            EncryptedKey = "encrypted_demo_value",
                            JoinedAt = new DateTime(2025, 1, 10, 8, 12, 0, 0, DateTimeKind.Utc),
                            Nickname = "Mod Quan",
                            Role = (byte)1,
                            ShowNotifications = (byte)2,
                            UserID = "U0000002"
                        },
                        new
                        {
                            MemberID = "M0000005",
                            ConversationID = "C0000002",
                            EncryptedKey = "encrypted_demo_value",
                            JoinedAt = new DateTime(2025, 1, 10, 8, 12, 0, 0, DateTimeKind.Utc),
                            Nickname = "Linh",
                            Role = (byte)0,
                            ShowNotifications = (byte)2,
                            UserID = "U0000003"
                        });
                });

            modelBuilder.Entity("SecureChat.Models.Friend", b =>
                {
                    b.Property<string>("FriendshipID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("friendship_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("UserAID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("user_a_id");

                    b.Property<string>("UserBID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("user_b_id");

                    b.HasKey("FriendshipID");

                    b.HasIndex("UserBID");

                    b.HasIndex("UserAID", "UserBID")
                        .IsUnique()
                        .HasDatabaseName("uq_friends_pair");

                    b.ToTable("Friends", t =>
                        {
                            t.HasCheckConstraint("chk_friends_order", "user_a_id < user_b_id");
                        });

                    b.HasData(
                        new
                        {
                            FriendshipID = "F0000001",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 5, 0, 0, DateTimeKind.Utc),
                            UserAID = "U0000001",
                            UserBID = "U0000002"
                        });
                });

            modelBuilder.Entity("SecureChat.Models.FriendRequest", b =>
                {
                    b.Property<string>("RequestID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("RecipientID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("recipient_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("responded_at");

                    b.Property<string>("SenderID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("sender_id");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.HasKey("RequestID");

                    b.HasIndex("RecipientID", "Status")
                        .HasDatabaseName("idx_friend_req_receiver");

                    b.HasIndex("SenderID", "RecipientID")
                        .IsUnique()
                        .HasDatabaseName("uq_friendreq_pair");

                    b.ToTable("FriendRequests");

                    b.HasData(
                        new
                        {
                            RequestID = "RQ000001",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 8, 0, 0, DateTimeKind.Utc),
                            RecipientID = "U0000001",
                            SenderID = "U0000003",
                            Status = (byte)0
                        });
                });

            modelBuilder.Entity("SecureChat.Models.Message", b =>
                {
                    b.Property<string>("MessageID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("message_id");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<string>("ContentIV")
                        .HasColumnType("longtext")
                        .HasColumnName("content_iv");

                    b.Property<string>("ConversationID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edited_at");

                    b.Property<string>("OriginalSenderID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("original_sender_id");

                    b.Property<string>("ReplyToID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("reply_to_id");

                    b.Property<string>("SenderID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("message_type");

                    b.HasKey("MessageID");

                    b.HasIndex("OriginalSenderID");

                    b.HasIndex("ReplyToID");

                    b.HasIndex("SenderID")
                        .HasDatabaseName("idx_messages_sender");

                    b.HasIndex("ConversationID", "SentAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_messages_conversation");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageID = "MSG00001",
                            Content = "hello bro",
                            ContentIV = "iv_demo_value",
                            ConversationID = "C0000001",
                            OriginalSenderID = "U0000001",
                            SenderID = "M0000001",
                            SentAt = new DateTime(2025, 1, 10, 8, 15, 0, 0, DateTimeKind.Utc),
                            Type = (byte)0
                        },
                        new
                        {
                            MessageID = "MSG00002",
                            Content = "check API ch?a?",
                            ContentIV = "iv_demo_value",
                            ConversationID = "C0000001",
                            OriginalSenderID = "U0000002",
                            ReplyToID = "MSG00001",
                            SenderID = "M0000002",
                            SentAt = new DateTime(2025, 1, 10, 8, 18, 0, 0, DateTimeKind.Utc),
                            Type = (byte)0
                        },
                        new
                        {
                            MessageID = "MSG00003",
                            Content = "encrypt ok ch?a?",
                            ContentIV = "iv_demo_value",
                            ConversationID = "C0000001",
                            OriginalSenderID = "U0000001",
                            SenderID = "M0000001",
                            SentAt = new DateTime(2025, 1, 10, 8, 21, 0, 0, DateTimeKind.Utc),
                            Type = (byte)0
                        },
                        new
                        {
                            MessageID = "MSG00004",
                            Content = "hello team, test group chat nhé",
                            ContentIV = "iv_demo_value",
                            ConversationID = "C0000002",
                            OriginalSenderID = "U0000001",
                            SenderID = "M0000003",
                            SentAt = new DateTime(2025, 1, 10, 8, 15, 0, 0, DateTimeKind.Utc),
                            Type = (byte)0
                        },
                        new
                        {
                            MessageID = "MSG00005",
                            Content = "ok bro, SignalR realtime ?n",
                            ContentIV = "iv_demo_value",
                            ConversationID = "C0000002",
                            OriginalSenderID = "U0000002",
                            ReplyToID = "MSG00004",
                            SenderID = "M0000004",
                            SentAt = new DateTime(2025, 1, 10, 8, 18, 0, 0, DateTimeKind.Utc),
                            Type = (byte)0
                        },
                        new
                        {
                            MessageID = "MSG00006",
                            Content = "done r?i, nh? test forgot password",
                            ContentIV = "iv_demo_value",
                            ConversationID = "C0000002",
                            OriginalSenderID = "U0000003",
                            SenderID = "M0000005",
                            SentAt = new DateTime(2025, 1, 10, 8, 21, 0, 0, DateTimeKind.Utc),
                            Type = (byte)0
                        },
                        new
                        {
                            MessageID = "MSG00007",
                            Content = "file sent: api_test_plan.pdf",
                            ContentIV = "iv_demo_value",
                            ConversationID = "C0000002",
                            OriginalSenderID = "U0000001",
                            ReplyToID = "MSG00006",
                            SenderID = "M0000003",
                            SentAt = new DateTime(2025, 1, 10, 8, 24, 0, 0, DateTimeKind.Utc),
                            Type = (byte)4
                        });
                });

            modelBuilder.Entity("SecureChat.Models.MessageAttachment", b =>
                {
                    b.Property<string>("AttachmentID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("attachment_id");

                    b.Property<int?>("DurationSecs")
                        .HasColumnType("int")
                        .HasColumnName("duration_secs");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileIv")
                        .HasColumnType("longtext")
                        .HasColumnName("file_iv");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileURL")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_url");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("MessageID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("message_id");

                    b.Property<string>("ThumbnailIv")
                        .HasColumnType("longtext")
                        .HasColumnName("thumbnail_iv");

                    b.Property<string>("ThumbnailURL")
                        .HasColumnType("longtext")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("AttachmentID");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("idx_attachments_hash");

                    b.HasIndex("MessageID");

                    b.ToTable("MessageAttachments");

                    b.HasData(
                        new
                        {
                            AttachmentID = "A0000001",
                            FileHash = "hash_demo_value",
                            FileIv = "iv_demo_value",
                            FileName = "api_test_plan.pdf",
                            FileSize = 102400L,
                            FileType = "application/pdf",
                            FileURL = "encrypted_demo_value",
                            MessageID = "MSG00007",
                            UploadedAt = new DateTime(2025, 1, 10, 8, 24, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SecureChat.Models.MessageMention", b =>
                {
                    b.Property<string>("MessageID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("message_id");

                    b.Property<string>("MemberID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("member_id");

                    b.HasKey("MessageID", "MemberID");

                    b.HasIndex("MemberID")
                        .HasDatabaseName("idx_mentions_user");

                    b.ToTable("MessageMentions");

                    b.HasData(
                        new
                        {
                            MessageID = "MSG00005",
                            MemberID = "M0000005"
                        });
                });

            modelBuilder.Entity("SecureChat.Models.MessagePin", b =>
                {
                    b.Property<string>("MessageID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("message_id");

                    b.Property<string>("ConversationID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("PinnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("pinned_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("PinnedBy")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("pinned_by");

                    b.HasKey("MessageID", "ConversationID");

                    b.HasIndex("ConversationID")
                        .HasDatabaseName("idx_message_pins_conv");

                    b.HasIndex("PinnedBy");

                    b.ToTable("MessagePins");

                    b.HasData(
                        new
                        {
                            MessageID = "MSG00006",
                            ConversationID = "C0000002",
                            PinnedAt = new DateTime(2025, 1, 10, 8, 28, 0, 0, DateTimeKind.Utc),
                            PinnedBy = "M0000003"
                        });
                });

            modelBuilder.Entity("SecureChat.Models.MessageReaction", b =>
                {
                    b.Property<string>("ReactionID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("reaction_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("member_id");

                    b.Property<string>("MessageID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("message_id");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("reaction");

                    b.HasKey("ReactionID");

                    b.HasIndex("MemberID");

                    b.HasIndex("MessageID", "MemberID", "Reaction")
                        .IsUnique()
                        .HasDatabaseName("uq_reaction_msg_users");

                    b.ToTable("MessageReactions");

                    b.HasData(
                        new
                        {
                            ReactionID = "RE000001",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 21, 0, 0, DateTimeKind.Utc),
                            MemberID = "M0000001",
                            MessageID = "MSG00002",
                            Reaction = "??"
                        });
                });

            modelBuilder.Entity("SecureChat.Models.MessageStatus", b =>
                {
                    b.Property<string>("StatusID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivered_at");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("member_id");

                    b.Property<string>("MessageID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at");

                    b.HasKey("StatusID");

                    b.HasIndex("MemberID", "ReadAt")
                        .HasDatabaseName("idx_msg_status_user");

                    b.HasIndex("MessageID", "MemberID")
                        .IsUnique()
                        .HasDatabaseName("uq_status_msg_user");

                    b.ToTable("MessageStatuses");

                    b.HasData(
                        new
                        {
                            StatusID = "ST000001",
                            DeliveredAt = new DateTime(2025, 1, 10, 8, 15, 0, 0, DateTimeKind.Utc),
                            MemberID = "M0000002",
                            MessageID = "MSG00001",
                            ReadAt = new DateTime(2025, 1, 10, 8, 18, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StatusID = "ST000002",
                            DeliveredAt = new DateTime(2025, 1, 10, 8, 18, 0, 0, DateTimeKind.Utc),
                            MemberID = "M0000001",
                            MessageID = "MSG00002",
                            ReadAt = new DateTime(2025, 1, 10, 8, 21, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StatusID = "ST000003",
                            DeliveredAt = new DateTime(2025, 1, 10, 8, 21, 0, 0, DateTimeKind.Utc),
                            MemberID = "M0000003",
                            MessageID = "MSG00006",
                            ReadAt = new DateTime(2025, 1, 10, 8, 24, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SecureChat.Models.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarURL")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BioText")
                        .HasColumnType("longtext")
                        .HasColumnName("bio_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("email");

                    b.Property<string>("HashedBKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hashed_b_key");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hashed_password");

                    b.Property<string>("HashedRecoveryKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hashed_recovery_key");

                    b.Property<string>("KeySalt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("key_salt");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("public_key");

                    b.Property<bool>("ShowOnlineStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_online_status");

                    b.Property<bool>("ShowReadStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_read_status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("username");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = "U0000001",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Hoang Hieu",
                            Email = "u1@securechat.local",
                            HashedBKey = "hash_demo_value",
                            HashedPassword = "hash_demo_value",
                            HashedRecoveryKey = "hash_demo_value",
                            KeySalt = "hash_demo_value",
                            PublicKey = "encrypted_demo_value",
                            ShowOnlineStatus = true,
                            ShowReadStatus = true,
                            UpdatedAt = new DateTime(2025, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Username = "hoanghieu"
                        },
                        new
                        {
                            UserID = "U0000002",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Minh Quan",
                            Email = "u2@securechat.local",
                            HashedBKey = "hash_demo_value",
                            HashedPassword = "hash_demo_value",
                            HashedRecoveryKey = "hash_demo_value",
                            KeySalt = "hash_demo_value",
                            PublicKey = "encrypted_demo_value",
                            ShowOnlineStatus = true,
                            ShowReadStatus = true,
                            UpdatedAt = new DateTime(2025, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Username = "minhquan"
                        },
                        new
                        {
                            UserID = "U0000003",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Linh Nguyen",
                            Email = "u3@securechat.local",
                            HashedBKey = "hash_demo_value",
                            HashedPassword = "hash_demo_value",
                            HashedRecoveryKey = "hash_demo_value",
                            KeySalt = "hash_demo_value",
                            PublicKey = "encrypted_demo_value",
                            ShowOnlineStatus = true,
                            ShowReadStatus = true,
                            UpdatedAt = new DateTime(2025, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Username = "linhnguyen"
                        });
                });

            modelBuilder.Entity("SecureChat.Models.UserSession", b =>
                {
                    b.Property<string>("SessionID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_name");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastUsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_used_at")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("user_id");

                    b.HasKey("SessionID");

                    b.HasIndex("RefreshToken")
                        .IsUnique()
                        .HasDatabaseName("uq_sessions_refresh_token");

                    b.HasIndex("UserID");

                    b.ToTable("UserSessions");

                    b.HasData(
                        new
                        {
                            SessionID = "S0000001",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 2, 0, 0, DateTimeKind.Utc),
                            DeviceName = "Windows 11 Dev Machine",
                            ExpiresAt = new DateTime(2025, 2, 9, 8, 2, 0, 0, DateTimeKind.Utc),
                            LastUsedAt = new DateTime(2025, 1, 10, 8, 2, 0, 0, DateTimeKind.Utc),
                            RefreshToken = "refresh_token_demo_u1",
                            UserID = "U0000001"
                        },
                        new
                        {
                            SessionID = "S0000002",
                            CreatedAt = new DateTime(2025, 1, 10, 8, 2, 0, 0, DateTimeKind.Utc),
                            DeviceName = "Windows 11 QA Laptop",
                            ExpiresAt = new DateTime(2025, 2, 9, 8, 2, 0, 0, DateTimeKind.Utc),
                            LastUsedAt = new DateTime(2025, 1, 10, 8, 2, 0, 0, DateTimeKind.Utc),
                            RefreshToken = "refresh_token_demo_u2",
                            UserID = "U0000002"
                        });
                });

            modelBuilder.Entity("SecureChat.Models.BlockedUser", b =>
                {
                    b.HasOne("SecureChat.Models.User", "Blocked")
                        .WithMany()
                        .HasForeignKey("BlockedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.User", "Blocker")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("BlockerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("SecureChat.Models.CallLog", b =>
                {
                    b.HasOne("SecureChat.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.ConversationMember", "StartedByMember")
                        .WithMany()
                        .HasForeignKey("StartedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("StartedByMember");
                });

            modelBuilder.Entity("SecureChat.Models.CallParticipant", b =>
                {
                    b.HasOne("SecureChat.Models.CallLog", "Call")
                        .WithMany("Participants")
                        .HasForeignKey("CallID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.ConversationMember", "Member")
                        .WithMany("CallsJoined")
                        .HasForeignKey("ParticipantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Call");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SecureChat.Models.Conversation", b =>
                {
                    b.HasOne("SecureChat.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SecureChat.Models.Message", "LastMessage")
                        .WithMany()
                        .HasForeignKey("LastMessageID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("LastMessage");
                });

            modelBuilder.Entity("SecureChat.Models.ConversationMember", b =>
                {
                    b.HasOne("SecureChat.Models.Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.Message", "LastReadMessage")
                        .WithMany()
                        .HasForeignKey("LastReadMsgID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SecureChat.Models.User", "User")
                        .WithMany("ConversationMemberships")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("LastReadMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureChat.Models.Friend", b =>
                {
                    b.HasOne("SecureChat.Models.User", "UserA")
                        .WithMany("FriendshipsA")
                        .HasForeignKey("UserAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.User", "UserB")
                        .WithMany("FriendshipsB")
                        .HasForeignKey("UserBID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("SecureChat.Models.FriendRequest", b =>
                {
                    b.HasOne("SecureChat.Models.User", "Recipient")
                        .WithMany("FriendRequestsReceived")
                        .HasForeignKey("RecipientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.User", "Sender")
                        .WithMany("FriendRequestsSent")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SecureChat.Models.Message", b =>
                {
                    b.HasOne("SecureChat.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.User", "OriginalSender")
                        .WithMany()
                        .HasForeignKey("OriginalSenderID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SecureChat.Models.Message", "ReplyTo")
                        .WithMany()
                        .HasForeignKey("ReplyToID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SecureChat.Models.ConversationMember", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Conversation");

                    b.Navigation("OriginalSender");

                    b.Navigation("ReplyTo");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SecureChat.Models.MessageAttachment", b =>
                {
                    b.HasOne("SecureChat.Models.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecureChat.Models.MessageMention", b =>
                {
                    b.HasOne("SecureChat.Models.ConversationMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.Message", "Message")
                        .WithMany("Mentions")
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecureChat.Models.MessagePin", b =>
                {
                    b.HasOne("SecureChat.Models.Conversation", "Conversation")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.ConversationMember", "Member")
                        .WithMany()
                        .HasForeignKey("PinnedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conversation");

                    b.Navigation("Member");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecureChat.Models.MessageReaction", b =>
                {
                    b.HasOne("SecureChat.Models.ConversationMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.Message", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecureChat.Models.MessageStatus", b =>
                {
                    b.HasOne("SecureChat.Models.ConversationMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureChat.Models.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecureChat.Models.UserSession", b =>
                {
                    b.HasOne("SecureChat.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureChat.Models.CallLog", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("SecureChat.Models.Conversation", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");

                    b.Navigation("PinnedMessages");
                });

            modelBuilder.Entity("SecureChat.Models.ConversationMember", b =>
                {
                    b.Navigation("CallsJoined");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("SecureChat.Models.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Mentions");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("SecureChat.Models.User", b =>
                {
                    b.Navigation("BlockedUsers");

                    b.Navigation("ConversationMemberships");

                    b.Navigation("FriendRequestsReceived");

                    b.Navigation("FriendRequestsSent");

                    b.Navigation("FriendshipsA");

                    b.Navigation("FriendshipsB");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
